# Generated by Django 6.0.4 on 2026-04-15 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('agencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.agencia')),
            ],
        ),
        migrations.CreateModel(
            name='Poliza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=255)),
                ('prima', models.DecimalField(decimal_places=2, max_digits=10)),
                ('porcentaje_comision', models.DecimalField(decimal_places=2, max_digits=5)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.agente')),
            ],
        ),
    ]
