# Generated by Django 6.0.4 on 2026-04-15 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_comision'),
    ]

    operations = [
        migrations.AddField(
            model_name='poliza',
            name='numero_poliza',
            field=models.CharField(default=654465465465, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
