# Generated by Django 6.0.4 on 2026-04-15 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_poliza_numero_poliza'),
    ]

    operations = [
        migrations.AddField(
            model_name='poliza',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poliza',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
