# Generated by Django 6.0.4 on 2026-04-15 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_poliza_fecha_inicio_poliza_fecha_vencimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='poliza',
            name='tipo',
            field=models.CharField(choices=[('auto', 'Auto'), ('vida', 'Vida'), ('salud', 'Salud'), ('hogar', 'Hogar'), ('otros', 'Otros')], default='otros', max_length=20),
        ),
    ]
