# Generated by Django 6.0.4 on 2026-04-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_poliza_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poliza',
            old_name='prima',
            new_name='prima_neta',
        ),
        migrations.AddField(
            model_name='poliza',
            name='recargos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
