# Generated by Django 6.0.4 on 2026-04-16 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_prima_poliza_prima_neta_poliza_recargos'),
    ]

    operations = [
        migrations.AddField(
            model_name='comision',
            name='porcentaje_comision_snapshot',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comision',
            name='prima_neta_snapshot',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comision',
            name='tipo',
            field=models.CharField(choices=[('alta', 'Alta'), ('renovacion', 'Renovación'), ('ajuste', 'Ajuste')], default='alta', max_length=20),
        ),
        migrations.AlterField(
            model_name='comision',
            name='poliza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comisiones', to='core.poliza'),
        ),
    ]
